/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import static form.JPSell.checkNumber;
import java.awt.Color;
import java.awt.PrintJob;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.net.www.MessageHeader;

/**
 *
 * @author Love JAV
 */
public class JPBill extends javax.swing.JPanel {

    /**
     * Creates new form JPBill
     */
    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;
    javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel(); 
    public JPBill() {
        initComponents();
//        Vector v = new Vector();
//        v.add("Số Thứ Tự"); v.add("Tên Khách Hàng"); v.add("Số Lần Giao Dịch"); v.add("Thanh Toán Hết");
//        tbCustomers.setModel(dtm);
//        dtm.setColumnIdentifiers(v);
        jPanel1.setOpaque(false);
        jPanel3.setOpaque(false);
        jPanel4.setOpaque(false);
        jPanel5.setOpaque(false);
        tbCustomers.getTableHeader().setReorderingAllowed(false);
        tbCustomers.getTableHeader().setResizingAllowed(false);
        
        try{
            conn = ConnectionDB.connectionDB.getConnection();
            showHoaDon();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
     public static boolean checkNumber(String s) throws Exception 
    {
        for(int i =0 ; i< s.length(); i++){
            if(Character.isDigit(s.charAt(i))){
               
            }else return false;
        }
        return true;
    }
         public String textFormat(double d){
        NumberFormat formatter = NumberFormat.getInstance();
        String moneyString = formatter.format(d);
        
        return moneyString;
    }
    public String textFormat(String s){
        NumberFormat formatter = NumberFormat.getInstance();
        String moneyString = formatter.format(s);
        
        return moneyString;
    }
    public long moneyFormat(String s) throws ParseException{
        NumberFormat format = NumberFormat.getInstance(Locale.JAPANESE);
        Number number = format.parse(s);
        
        return (long)number;
    }
    public void showHoaDon(){
        Vector cols = new Vector();
        
        cols.addElement("Mã HD");
        cols.addElement("TênKH");
        cols.addElement("Tổng Tiền");
        cols.addElement("Đã Trả");
        cols.addElement("Còn Nợ");
        cols.addElement("Số Dư");
        cols.addElement("Ngày Giao Dịch");
        Vector rows = new Vector();
        
        String sql = "SELECT hd.maHD, kh.TenKH, hd.TongTien, KH.DaTra, kh.ConNO, kh.SoDu, hd.NgayLap"
                + "   FROM HoaDOn hd, KhachHang kh"
                + "   WHERE hd.makh = kh.makh";
        try{
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            while(rs.next()){
               String tongtien = textFormat(rs.getDouble("TongTien"));
               String datra = textFormat(rs.getDouble("DaTra"));
               String conno = textFormat(rs.getDouble("ConNo"));
               String sodu = textFormat(rs.getDouble("SoDu"));
               
               Vector data = new Vector();
               data.addElement(rs.getString("MaHD"));
               data.addElement(rs.getString("TenKH"));
               data.addElement(tongtien);
               data.addElement(datra);
               data.addElement(conno);
               data.addElement(sodu);
               data.addElement(rs.getString("NgayLap"));
        
               rows.add(data);
            }
            tbCustomers.setModel(new DefaultTableModel(rows,cols));
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void EditCTHD(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTongTien1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbSoLanDG = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbDaTT = new javax.swing.JLabel();
        txtTraTiep = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbSoDu = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbConNo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1226, 796));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Tổng  :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("VNĐ");

        txtTongTien.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Số Lượng");

        txtTongTien1.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(97, 97, 97))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 700, 430, 60));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));

        tbCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCustomers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 680, 560));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTimKiem.setPreferredSize(new java.awt.Dimension(6, 6));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        jButton1.setText("Tìm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 330, 50));

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Hiển Thị Tất Cả");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Chưa Thanh Toán");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 330, 30));

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Top Mua Hàng Tháng");

        jButton4.setText("Tìm");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Từ Ngày");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đến Ngày");

        jButton6.setText("Top Mua Năm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(35, 35, 35))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 490, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Số Lần Giao Dịch   :");

        lbSoLanDG.setBackground(new java.awt.Color(255, 204, 204));
        lbSoLanDG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tổng Tiền                :");

        lbTongTien.setBackground(new java.awt.Color(255, 204, 204));
        lbTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Đã Thanh Toán      :");

        jLabel10.setBackground(new java.awt.Color(255, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Trả Tiếp                   :");

        lbDaTT.setBackground(new java.awt.Color(255, 204, 204));
        lbDaTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtTraTiep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTraTiepKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("VNĐ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("VNĐ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("VNĐ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("VNĐ");

        jLabel12.setBackground(new java.awt.Color(255, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Số Dư                        :");

        lbSoDu.setBackground(new java.awt.Color(255, 204, 204));
        lbSoDu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("VNĐ");

        lbConNo.setBackground(new java.awt.Color(255, 204, 204));
        lbConNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Còn Nợ                      :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbSoLanDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDaTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTraTiep)
                            .addComponent(lbSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbConNo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSoLanDG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDaTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbConNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTraTiep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 320, 230));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setText("Tất Cả Giao Dịch");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Chi Tiết Giao Dịch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setText("Cập Nhật");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btPrint.setText("In Giao Dịch");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(btPrint))
                .addContainerGap())
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 360, 80));

        jLabel3.setText("Mã HD:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 30));

        txtTenKH.setEditable(false);
        txtTenKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTenKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });
        add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tên KH:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 50, 30));

        txtMaHD.setEditable(false);
        txtMaHD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMaHD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));

        jButton8.setText("Nhập từ Excel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 210, 30));

        jButton9.setText("Xóa Hóa Đơn");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mages/main1.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tbCustomers.setEnabled(false);
        Vector cols = new Vector();
        
        cols.addElement("Số Thứ Tự");
        cols.addElement("Tên Sản Phẩm");
        cols.addElement("Giá Bán");
        cols.addElement("Số Lượng");
        cols.addElement("Thành Tiền");
        cols.addElement("Ngày Lập");
        
        int count = 0;

        
        String sql = "Select cthd.tensp,cthd.giaban,cthd.soluong,cthd.thanhtien,hd.ngaylap,hd.tongtien, hd.datra, hd.Conno, hd.sodu"
                + "   from ChitietHoaDon cthd, hoadon hd"
                + "   where cthd.mahd = hd.mahd and cthd.mahd = ?";
        Vector rows = new Vector();
        
        try{
            
            int i = 1;
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtMaHD.getText().toString());
            rs = stmt.executeQuery();
            while(rs.next()){
                String tongtien = textFormat(rs.getDouble("TongTien"));
                String datra = textFormat(rs.getDouble("DaTra"));
                String conno = textFormat(rs.getDouble("ConNo"));
                String sodu = textFormat(rs.getDouble("SoDu"));
                String giaban = textFormat(rs.getDouble("GiaBan"));
                String thanhtien = textFormat(rs.getDouble("ThanhTien"));
                Vector data = new Vector();
                
                data.addElement(i);
                data.addElement(rs.getString("tensp"));
                data.addElement(giaban);
                data.addElement(rs.getFloat("SoLuong"));
                data.addElement(thanhtien);
                data.addElement(rs.getString("Ngaylap"));
                
                lbSoLanDG.setText(Integer.toString(count));
                lbTongTien.setText(tongtien);
                lbDaTT.setText(datra);
                lbConNo.setText(conno);
                lbSoDu.setText(sodu);
                txtTongTien.setText(tongtien);
                rows.add(data);
                i++;
            }    
            tbCustomers.setModel(new DefaultTableModel(rows,cols));   
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tbCustomers.setEnabled(true);
        showHoaDon();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCustomersMouseClicked
        // TODO add your handling code here:
        int row = tbCustomers.getSelectedRow();
        
        if(row != -1){
            txtMaHD.setText(tbCustomers.getValueAt(row,0).toString());
            txtTenKH.setText(tbCustomers.getValueAt(row,1).toString());
            
        }
    }//GEN-LAST:event_tbCustomersMouseClicked

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        // TODO add your handling code here:
       try{
           PrinterJob printerJob = PrinterJob.getPrinterJob();
           MessageFormat header [] = new MessageFormat[13];
           int i = 0;
            header[i++] = new MessageFormat("");
            header[i++] = new MessageFormat("                                                                     Cửa Hàng Vật Liệu Xây Dựng MIẾN NHẮC");
            header[i++] = new MessageFormat("                                                                     Địa Chỉ : Số 1 - Quảng Bị - Chương Mỹ");
            header[i++] = new MessageFormat("                                                                     Số Điện Thoại: 096 85645 488");
            header[i++] = new MessageFormat("");
            header[i++] = new MessageFormat("                                                        HÓA ĐƠN BÁN HÀNG");
            header[i++] = new MessageFormat("");
            header[i++] = new MessageFormat("                                                     Ngày       Tháng       Năm");
            header[i++] = new MessageFormat("");
            header[i++] = new MessageFormat("Mã Hóa Đơn    :    " + txtMaHD.getText().trim());
            header[i++] = new MessageFormat("Khách Hàng    :    " + txtTenKH.getText().trim());
//            header[i++] = new MessageFormat("Số Điện Thoại :    " + txtSDT.getText().trim());
//            header[i++] = new MessageFormat("Địa Chỉ            :    " + txtDiaChi.getText().trim());
            
            MessageFormat[] footer = new MessageFormat[13];
            int j =0 ;

            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat(""
            + "                                                                                                   Số Lượng          :    ");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat(""
            + "                                                                                                   Tổng Tiền          :    " + lbTongTien.getText().trim() +"  vnđ");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat(""
            + "                                                                                                   Đã Thanh Toán :    " + lbDaTT.getText().trim() +"  vnđ");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat(""
            + "                                                                                                   Còn Nợ              :    " + lbConNo.getText().trim() +"  vnđ");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat(""
            + "                                                                                                   Số Dư                :    " + lbSoDu.getText().trim() +"  vnđ");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat("");
            footer[j++] = new MessageFormat("           Khách Hàng"
            + "                                                                                                   Người Bán Hàng");
            
            printerJob.setPrintable(new MyTablePrintable(tbCustomers, JTable.PrintMode.FIT_WIDTH, header, footer));
            printerJob.print();
       }catch(Exception ex){
           ex.printStackTrace();
       }
        
    }//GEN-LAST:event_btPrintActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        tbCustomers.setEnabled(true);
        showHoaDon();
        lbDaTT.setText("");
        lbConNo.setText("");
        lbSoDu.setText("");
        lbSoLanDG.setText("");
        lbTongTien.setText("");
        txtTongTien.setText("");
        txtMaHD.setText("");
        txtTenKH.setText("");
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        tbCustomers.setEnabled(true);
        Vector cols = new Vector();
        
        cols.addElement("Mã HD");
        cols.addElement("TênKH");
        cols.addElement("Tiền");
        cols.addElement("Đã Trả");
        cols.addElement("Còn Nợ");
        cols.addElement("Số Dư");
        cols.addElement("Ngày Giao Dịch");
        
        Vector rows = new Vector();
        
        String sql = "SELECT hd.maHD, kh.TenKH, hd.TongTien, KH.DaTra, kh.ConNO, kh.SoDu, hd.NgayLap"
                + "   FROM HoaDOn hd, KhachHang kh"
                + "   WHERE hd.makh = kh.makh";
        
        try{
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            while(rs.next()){
               if(rs.getDouble("ConNo") > 0){
                    String tongtien = textFormat(rs.getDouble("TongTien"));
                    String datra = textFormat(rs.getDouble("DaTra"));
                    String conno = textFormat(rs.getDouble("ConNo"));
                    String sodu = textFormat(rs.getDouble("SoDu"));
                    
                    Vector data = new Vector();
                    data.addElement(rs.getString("MaHD"));
                    data.addElement(rs.getString("TenKH"));
                    data.addElement(tongtien);
                    data.addElement(datra);
                    data.addElement(conno);
                    data.addElement(sodu);
                    data.addElement(rs.getString("NgayLap"));

                    rows.add(data);
               }
            }
            tbCustomers.setModel(new DefaultTableModel(rows,cols));
        }catch(Exception ex){
            ex.printStackTrace();
        }
        lbDaTT.setText("");
        lbConNo.setText("");
        lbSoDu.setText("");
        lbSoLanDG.setText("");
        lbTongTien.setText("");
        txtTongTien.setText("");
        txtMaHD.setText("");
        txtTenKH.setText("");
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void txtTraTiepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTraTiepKeyPressed
        // TODO add your handling code here:
        try{
           
            
            if(checkNumber(txtTraTiep.getText()) == true){
                if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                    long tongtien = moneyFormat(lbTongTien.getText().toString().trim());
                    long sodu = moneyFormat(txtTraTiep.getText().trim()) - moneyFormat(lbConNo.getText().trim());
                    long lbsodu = moneyFormat(lbSoDu.getText().toString().trim()) + sodu;
                    long lbconno = moneyFormat(lbConNo.getText().toString().trim()) - moneyFormat(txtTraTiep.getText().trim());
                    long lbdatt = moneyFormat(lbDaTT.getText().toLowerCase().trim()) + moneyFormat(txtTraTiep.getText().trim());
                    
//                    double sodu = Double.parseDouble(txtTraTiep.getText()) - Double.parseDouble(lbConNo.getText());
//
//                    double lbsodu = Double.parseDouble(lbSoDu.getText()) + sodu;
//                    double lbconno = Double.parseDouble(lbConNo.getText()) - Double.parseDouble(txtTraTiep.getText());
//                    double lbdatt = Double.parseDouble(lbDaTT.getText()) + Double.parseDouble(txtTraTiep.getText());

                    lbSoDu.setText(textFormat(lbsodu));
                    lbConNo.setText(textFormat(lbconno));
                    lbDaTT.setText(textFormat(lbdatt));
                    if(lbconno < 0)
                    lbConNo.setText("0.0");
                    if(lbsodu < 0)
                    lbSoDu.setText("0.0");
                    txtTraTiep.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Bạn Phải Nhập Số", "Nhập Lại", -1);
                txtTraTiep.setText("");
            }

        }catch(Exception ex){
            Logger.getLogger(JPSell.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtTraTiepKeyPressed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        // TODO add your handling code here:
         String sql =  "SELECT hd.maHD, kh.TenKH, hd.TongTien, KH.DaTra, kh.ConNO, kh.SoDu, hd.NgayLap"
                    + " FROM HoaDOn hd, KhachHang kh"
                    + " where kh.TenKH like '%" + txtTimKiem.getText() + "%' and hd.makh = kh.makh";
        
        Vector cols = new Vector();
        
        cols.addElement("Mã HD");
        cols.addElement("TênKH");
        cols.addElement("Tổng Tiền");
        cols.addElement("Đã Trả");
        cols.addElement("Còn Nợ");
        cols.addElement("Số Dư");
        cols.addElement("Ngày Giao Dịch");
       
        Vector rows = new Vector(); 
            try{
                stmt = conn.prepareStatement(sql);
                rs = stmt.executeQuery();
                
                while(rs.next()){
                    Vector data = new Vector();
                
                    data.addElement(rs.getString("MaHD"));
                    data.addElement(rs.getString("TenKH"));
                    data.addElement(rs.getDouble("TongTien"));
                    data.addElement(rs.getDouble("DaTra"));
                    data.addElement(rs.getDouble("ConNo"));
                    data.addElement(rs.getDouble("SoDu"));
                    data.addElement(rs.getString("NgayLap"));
                
                    rows.add(data);
                }
            
            }catch(Exception ex){
                ex.printStackTrace();
            }
            tbCustomers.setModel(new DefaultTableModel(rows,cols));
    }//GEN-LAST:event_txtTimKiemKeyTyped

    public void deleteKH(String tenkh, String maHD){
        String sql = "DELETE khachhang"
                + "   from khachhang kh, hoadon hd "
                + "   where tenkh = ? and hd.mahd = ? ";
        try{
            stmt = conn.prepareStatement(sql);
            stmt.setString(1,tenkh);
            stmt.setString(2, maHD);
            
            stmt.executeUpdate();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showConfirmDialog(this, ex.toString());
        }
    }
    public void deleteHD(String mahd){
        String sql = "DELETE from HoaDon where MaHD = ?";
        try{
            stmt = conn.prepareStatement(sql);
            stmt.setString(1,mahd);
            
            stmt.executeUpdate();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void deleteCTHD(String mahd){
        String sql = "DELETE chitiethoadon where MaHD = ?";
        try{
            stmt = conn.prepareStatement(sql);
            stmt.setString(1,mahd);
            stmt.executeUpdate();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showConfirmDialog(this, ex.toString());
        }
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int rs = JOptionPane.showConfirmDialog(this,"Xóa Hóa Đơn Này?","Xóa",1);
        if(rs == JOptionPane.YES_OPTION){
            deleteCTHD(txtMaHD.getText().trim());
            deleteKH(txtTenKH.getText().trim(), txtMaHD.getText().trim());
            deleteHD(txtMaHD.getText().trim());
            JOptionPane.showMessageDialog(this, "Thành Công!!!");
            showHoaDon();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
              if(updateCTHD() == true && updateHD() == true && updateKH() == true){
                 JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công!");
              }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConNo;
    private javax.swing.JLabel lbDaTT;
    private javax.swing.JLabel lbSoDu;
    private javax.swing.JLabel lbSoLanDG;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JTable tbCustomers;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTongTien1;
    private javax.swing.JTextField txtTraTiep;
    // End of variables declaration//GEN-END:variables
    public boolean updateKH(){
        String sql = "UPDATE KhachHang Set datra = ?, conno = ?, sodu = ?"
                + "   FROM Khachhang, HoaDon"
                + "   where  HoaDon.makh = khachhang.makh and mahd = ?";
        try{
            long lbsodu = moneyFormat(lbSoDu.getText().toString().trim());
            long lbconno = moneyFormat(lbConNo.getText().toString().trim());
            long lbdatt = moneyFormat(lbDaTT.getText().toLowerCase().trim());
            
            stmt = conn.prepareStatement(sql);
            stmt.setDouble(1, lbdatt);
            stmt.setDouble(2, lbconno);
            stmt.setDouble(3, lbsodu);
            stmt.setString(4, txtMaHD.getText().toString().trim());
            stmt.executeUpdate();
            return true;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return false;
    }
    public boolean updateHD(){
        String sql = "UPDATE HoaDon Set datra = ?, conno = ?, sodu = ?"
                + "   where  mahd = ?";
        try{
            long lbsodu = moneyFormat(lbSoDu.getText().toString().trim());
            long lbconno = moneyFormat(lbConNo.getText().toString().trim());
            long lbdatt = moneyFormat(lbDaTT.getText().toLowerCase().trim());
            
            stmt = conn.prepareStatement(sql);
            stmt.setDouble(1, lbdatt);
            stmt.setDouble(2, lbconno);
            stmt.setDouble(3, lbsodu);
            stmt.setString(4, txtMaHD.getText().toString());
            stmt.executeUpdate();
            return true;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return false;
    }
    public boolean updateCTHD(){
        String sql = "UPDATE ChiTietHoaDon Set datra = ?, conno = ?, sodu = ?"
                + "   where  mahd = ?";
        try{
            long lbsodu = moneyFormat(lbSoDu.getText().toString().trim());
            long lbconno = moneyFormat(lbConNo.getText().toString().trim());
            long lbdatt = moneyFormat(lbDaTT.getText().toLowerCase().trim());
            
            stmt = conn.prepareStatement(sql);
            stmt.setDouble(1, lbdatt);
            stmt.setDouble(2, lbconno);
            stmt.setDouble(3, lbsodu);
            stmt.setString(4, txtMaHD.getText().toString());
            stmt.executeUpdate();
            return true;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return false;
    }
}
